language: java

branches:
  only:
   - develop

sudo: enabled

addons:
  apt:
    packages:
      - oracle-java11-installer
      
jdk:  
 - oraclejdk11

before_install:
 - sudo apt-get update

install: true 

script:
 - mvn clean package install -Dmaven.javadoc.skip=true -B